services:
  backend:
    build: .
    container_name: smart_energy_backend
    # command: >
    #   bash -c "
    #     echo 'Checking database connectivity...';
    #     alembic revision --autogenerate -m 'auto migration' || true;
    #     echo 'Running migrations...';
    #     alembic upgrade head;
    #     echo 'Migrations complete. Starting server...';
    #     uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    #   "
    volumes:
      - .:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: smart_energy_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smartenergy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smartenergy}
      POSTGRES_DB: ${POSTGRES_DB:-smartenergy}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nats:
  #   image: nats:2.10-alpine
  #   container_name: smart_energy_nats
  #   restart: always
  #   ports:
  #     - "4222:4222"
  #     - "8222:8222"
  #   command: ["-js"]

  redis:
    image: redis:7
    container_name: smartenergy_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
        
  # wdb:
  #   image: kozea/wdb
  #   container_name: smart_energy_wdb
  #   restart: always
  #   ports:
  #     - "1984:1984"

volumes:
  postgres_data:
